name: videos_api
description: The interface and models for an API providing access to Videos.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  http: ^0.13.4
  video_player: ^2.2.19

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
