name: videos_repository
description: A repository that handles Video related requests.
version: 0.0.1
publish_to: none
homepage: null

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  videos_api:
    path: ../videos_api

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter: null
